spring:
  application:
    name: ant
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      batch-size: 16
      retries: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: test-consumer-group
server:
  port: 12345
  servlet:
    context-path: /ant
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: 127.0.0.1:${server.port}
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000